
import os
os.environ.setdefault('DATABASE_URL', "postgresql://neondb_owner:2i3lysDwVYoB@ep-billowing-violet-a2y3sv0k.eu-central-1.aws.neon.tech/mouth_widow_chair_401987")

os.environ.setdefault('STRIPE_SECRET_KEY_TEST', "sk_test_51QnJ4CBTWfUSHSrG5UTseeXqjDzHDLVoT8Qd4ukQa3OktUTc6IunV1AZurbiUHzuZtun5dj7q9QcxLgNvs5d9xGW00rnVkqHkA")

STRIPE_SECRET_KEY_TEST=sk_test_51QnJ47BMzPNz1e4lHz4rrrWTIQJGnlnnpkzrQm5yRR3qThq4taxKZUbwbf4q92fWxAonmYcDOQuOaTYegXgft83w00ClfFfrV0
